package tuanhiep.usa.algo.euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2_EvenFibonacci {

    public static void main(String[] args) {

        System.out.println(Problem2_EvenFibonacci.sumEvenFibonacci(4000000));

    }

    public static int sumEvenFibonacci(int n) {
        int fibo0 = 1;
        int fibo1 = 2;
        int generatedFibo = 0;
        int sum = 2;

        while (generatedFibo <= n) {
            generatedFibo = fibo0 + fibo1;
            fibo0 = fibo1;
            fibo1 = generatedFibo;
            if ((generatedFibo %2) == 0) {
                sum += generatedFibo;
            }

        }
        return sum;
    }
}
